name: Release CI
on:
  push:
    branches: master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14
      - name: Init npm package
        run: npm init -y
      - name: Install @koj/config
        run: npm install @koj/config
      - name: Create release.config.js
        run: echo 'module.exports = require("@koj/config").releaseMaster;' > release.config.js
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GIT_AUTHOR_NAME: "Koj Bot"
          GIT_AUTHOR_EMAIL: "bot@koj.co"
          GIT_COMMITTER_NAME: "Koj Bot"
          GIT_COMMITTER_EMAIL: "bot@koj.co"
